### ISSUE TITLE
RuntimeError: cuda runtime error (8) : invalid device function at /pytorch/torch/lib/THC/generic/THCTensorIndex.cu:648

### ISSUE THREAD

**Issue by GYM13** [lichengunc/mask-faster-rcnn#1]
Traceback (most recent call last):
  File "check_model.py", line 101, in <module>
    scores, boxes, net_conv, im_scale = im_detect(net, im)
  File "../tools/../lib/model/test.py", line 104, in im_detect
    _, scores, bbox_pred, rois, net_conv = net.test_image(blobs['data'], blobs['im_info'])
  File "../tools/../lib/nets/network.py", line 571, in test_image
    self.forward(image, im_info, None, None, mode='TEST')
  File "../tools/../lib/nets/network.py", line 541, in forward
    net_conv, rois, cls_prob, bbox_pred, mask_prob = self._predict()
  File "../tools/../lib/nets/network.py", line 468, in _predict
    rois = self._region_proposal(net_conv)
  File "../tools/../lib/nets/network.py", line 256, in _region_proposal
    rois, _ = self._proposal_layer(rpn_cls_prob, rpn_bbox_pred)
  File "../tools/../lib/nets/network.py", line 94, in _proposal_layer
    self._feat_stride, self._anchors, self._num_anchors)
  File "../tools/../lib/layer_utils/proposal_layer.py", line 61, in proposal_layer
    proposals = proposals[keep, :]
  File "/usr/lib64/python2.7/site-packages/torch/autograd/variable.py", line 78, in __getitem__
    return Index.apply(self, key)
  File "/usr/lib64/python2.7/site-packages/torch/autograd/_functions/tensor.py", line 87, in forward
    result = i.index(ctx.index)

**Comment by winterest** [comment]
Have you figured it out?

**Comment by Millielele** [comment]
cuda8.0  pytorch0.4.0  maybe work
