### ISSUE TITLE
result of slicing is an empty tensor

### ISSUE THREAD

**Issue by LQY404** [lichengunc/mask-faster-rcnn#9]
this problem happens randomly...............
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 141, in <module>
    max_iters=args.max_iters)
  File "/home/user/PycharmProjects/MAttNet/pyutils/mask-faster-rcnn/tools/../lib/model/train_val.py", line 367, in train_net
    sw.train_model(max_iters)
  File "/home/user/PycharmProjects/MAttNet/pyutils/mask-faster-rcnn/tools/../lib/model/train_val.py", line 284, in train_model
    self.net.train_step(blobs, self.optimizer)
  File "/home/user/PycharmProjects/MAttNet/pyutils/mask-faster-rcnn/tools/../lib/nets/network.py", line 595, in train_step
    self.forward(blobs['data'], blobs['im_info'], blobs['gt_boxes'], blobs['gt_masks'])
  File "/home/user/PycharmProjects/MAttNet/pyutils/mask-faster-rcnn/tools/../lib/nets/network.py", line 542, in forward
    net_conv, rois, cls_prob, bbox_pred, mask_prob = self._predict()
  File "/home/user/PycharmProjects/MAttNet/pyutils/mask-faster-rcnn/tools/../lib/nets/network.py", line 469, in _predict
    rois = self._region_proposal(net_conv)
  File "/home/user/PycharmProjects/MAttNet/pyutils/mask-faster-rcnn/tools/../lib/nets/network.py", line 254, in _region_proposal
    rois, _ = self._proposal_target_layer(rois, roi_scores)
  File "/home/user/PycharmProjects/MAttNet/pyutils/mask-faster-rcnn/tools/../lib/nets/network.py", line 203, in _proposal_target_layer
    rois, roi_scores, self._gt_boxes, self._gt_masks, self._num_classes)
  File "/home/user/PycharmProjects/MAttNet/pyutils/mask-faster-rcnn/tools/../lib/layer_utils/proposal_target_layer.py", line 65, in proposal_target_layer
    fg_rois_per_image, rois_per_image, _num_classes)
  File "/home/user/PycharmProjects/MAttNet/pyutils/mask-faster-rcnn/tools/../lib/layer_utils/proposal_target_layer.py", line 188, in _sample_rois
    print(labels[int(fg_rois_per_image):])
  File "/home/user/anaconda3/envs/mattnets/lib/python2.7/site-packages/torch/autograd/variable.py", line 78, in __getitem__
    return Index.apply(self, key)
  File "/home/user/anaconda3/envs/mattnets/lib/python2.7/site-packages/torch/autograd/_functions/tensor.py", line 89, in forward
    result = i.index(ctx.index)
ValueError: result of slicing is an empty tensor

can you help me, please....

**Comment by LQY404** [comment]
when i run this :
./experiments/scripts/train_mask_rcnn_notime.sh 0 refcoco res101 notime
